"""empty message

Revision ID: 121d113eadb3
Revises: ee132471f144
Create Date: 2024-09-16 01:02:12.750812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121d113eadb3'
down_revision: Union[str, None] = 'ee132471f144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_unique_constraint(None, 'coupons', ['coupon_number'])
    op.add_column('users', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'id')
    op.drop_constraint(None, 'coupons', type_='unique')
    op.drop_column('coupons', 'id')
    # ### end Alembic commands ###
