"""empty message

Revision ID: 230d1bf9cd43
Revises: ec99c5c5ce42
Create Date: 2024-09-16 06:52:05.897397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230d1bf9cd43'
down_revision: Union[str, None] = 'ec99c5c5ce42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('Admin', 'CoreMember', 'Lead', name='roleenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
