"""empty message

Revision ID: 855d51aec002
Revises: 36f37500b06a
Create Date: 2024-09-16 01:26:34.334958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '855d51aec002'
down_revision: Union[str, None] = '36f37500b06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('create_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'coupons', 'users', ['create_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.drop_column('coupons', 'create_user_id')
    # ### end Alembic commands ###
