"""empty message

Revision ID: 9fe866f30228
Revises: 230d1bf9cd43
Create Date: 2024-09-18 13:03:05.045485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe866f30228'
down_revision: Union[str, None] = '230d1bf9cd43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dept')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dept', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
