"""empty message

Revision ID: ec99c5c5ce42
Revises: 855d51aec002
Create Date: 2024-09-16 06:47:05.274411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec99c5c5ce42'
down_revision: Union[str, None] = '855d51aec002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('dept', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dept')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
