"""empty message

Revision ID: ee132471f144
Revises: 
Create Date: 2024-09-15 23:55:31.137634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee132471f144'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('coupons',
    sa.Column('coupon_number', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('create_user_email', sa.String(), nullable=False),
    sa.Column('create_user_name', sa.String(), nullable=False),
    sa.Column('discount_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['create_user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('coupon_number'),
    sa.UniqueConstraint('coupon_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupons')
    op.drop_table('users')
    # ### end Alembic commands ###
